In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("scores_privados.csv")

In [5]:
df.columns

Index(['DateSubmitted', 'SubmissionId', 'TeamId', 'UserName', 'TeamName',
       'IsSelected', 'PublicScore', 'PrivateScore'],
      dtype='object')

In [12]:
f=df["TeamName"].str.lower().str.contains("lombardo")
df.loc[f]

,DateSubmitted,SubmissionId,TeamId,UserName,TeamName,IsSelected,PublicScore,PrivateScore
310,2025-03-26 05:29:05,43675498,13523690,christianlombardo,christianlombardo,False,201403.103852,174658.217273
321,2025-03-26 13:53:03,43682008,13523690,christianlombardo,christianlombardo,False,217596.776204,181324.144332
361,2025-03-26 20:51:15,43688551,13523690,christianlombardo,christianlombardo,False,684074.632524,547441.169616
420,2025-03-27 14:53:28,43702946,13523690,christianlombardo,christianlombardo,False,164497.249288,145593.691881
423,2025-03-27 15:19:04,43703420,13523690,christianlombardo,christianlombardo,False,160081.158114,143747.718796
...,...,...,...,...,...,...,...,...
5770,2025-05-21 01:03:51,44925773,13523690,christianlombardo,christianlombardo,False,51938.130098,41310.811095
5773,2025-05-21 01:19:52,44926007,13523690,christianlombardo,christianlombardo,False,48078.262214,40761.379295
6149,2025-05-28 17:25:22,45138682,13523690,christianlombardo,christianlombardo,True,34405.043586,36071.852671
6151,2025-05-28 18:12:24,45139577,13523690,christianlombardo,christianlombardo,False,36548.193128,36396.837869
6163,2025-05-29 03:00:18,45147168,13523690,christianlombardo,christianlombardo,False,34421.498321,36104.119932

In [15]:
f=df["UserName"]=="christianlombardo"
df.loc[f,["DateSubmitted","PublicScore","PrivateScore","IsSelected"]].sort_values(by="PrivateScore",ascending=True).head(20)

            DateSubmitted   PublicScore  PrivateScore  IsSelected
5670  2025-05-20 19:15:55  34842.270544  34355.734065       False
5495  2025-05-19 14:55:10  35351.700367  34397.654993       False
5094  2025-05-16 21:46:13  35290.961460  34546.991967       False
5614  2025-05-20 01:49:12  34964.230003  34567.191605       False
5618  2025-05-20 02:00:35  32557.475678  35612.150719       False
5179  2025-05-17 00:24:43  32640.741075  35623.398091       False
5074  2025-05-16 21:06:15  32562.228436  35693.029265       False
5084  2025-05-16 21:22:33  32526.446476  35795.362844       False
6149  2025-05-28 17:25:22  34405.043586  36071.852671        True
6163  2025-05-29 03:00:18  34421.498321  36104.119932       False
6151  2025-05-28 18:12:24  36548.193128  36396.837869       False
5608  2025-05-20 01:24:28  45452.177133  36441.686110       False
5193  2025-05-17 00:42:17  35133.889157  36669.727860       False
4867  2025-05-15 19:16:26  40443.407665  36796.431646       False
4707  2025-05-14 21:43:07  35815.713373  37044.893241       False
4560  2025-05-13 21:42:49  39869.137419  37241.540886       False
4361  2025-05-12 22:18:17  36274.393423  37473.899754       False
4370  2025-05-12 22:59:44  35720.675429  37512.751972       False
4376  2025-05-12 23:20:13  44077.641179  37680.906902       False
4527  2025-05-13 19:18:59  39376.605999  37980.928188       False